class Apiv1.Message extends DS.Model
  fromCompany: DS.attr "string"
  senderEmail: DS.attr "string"
  subjectText: DS.attr "string"
  message: DS.attr "string"
  createdAt: DS.attr "date"
  updatedAt: DS.attr "date"
  phoneNumber: DS.attr "string"
  contactPerson: DS.attr "string"
  companyAddress: DS.attr "string"